# Generated by Django 5.0.3 on 2024-03-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_task_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(null=True),
        ),
    ]
